### ISSUE TITLE
Python 3の仮想環境を初期化するには、 $ pipenv --two を実行します。

### ISSUE THREAD

**Issue by terapyon** [cocoatomo/pipenv#3]
Python 3の仮想環境を初期化するには、 $ pipenv --two を実行します。
↓
「Python 2」が正解だと思います。

**Comment by cocoatomo** [comment]
https://github.com/cocoatomo/pipenv/commit/436d51640027c66b5aaf2dd81ac89705ff5d1bb2#diff-9f8391446dc9a9632f2137deee667f95R219

にて修正しました.
